version: '3.8'

services:
  materia-service:
    build: ./materia-service
    ports:
      - "8082:8082"
    env_file:
      - .env
    networks:
      - apuntesia-network

  apunte-service:
    build: ./apunte-service
    ports:
      - "8083:8083"
    env_file:
      - .env
    networks:
      - apuntesia-network

networks:
  apuntesia-network:
    driver: bridge