# Servidor
server.port=8082

# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.hikari.maximum-pool-size=15
spring.datasource.hikari.minimum-idle=3
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=600000

azure.tenant-id=c4f44f7e-f5c8-49a8-8f08-b39ffd2a6d43
azure.client-id=c98eba33-135d-40c4-9382-7166ce6af6f3